const Party = require("./../schema/partySchema");
const nodeMailer = require("nodemailer");
const tempPartyDetail = require("./../data/partyDoc.json");

exports.getParty = async (req, res, next) => {
  // const party = await Party.find();
  const party = tempPartyDetail;

  if (!party.length) {
    return res.status(400).json({ message: "No Data" });
  }

  res.status(200).json({
    message: "Below are all party",
    party,
  });
};

exports.createParty = async (req, res, next) => {
  const { name, contact, email, address } = req.body;

  const party = await Party.create({ name, contact, email, address });

  res.status(200).json({
    message: "Below is the party",
    party,
  });
};

exports.informParty = async (req, res, next) => {
  const awb = req.body;
  console.log(awb);

  const transporter = nodeMailer.createTransport({
    service: "gmail",
    auth: {
      user: "amansherpa70@gmail.com",
      pass: "rscyzlcosydnwokj",
    },
  });

  const mailOptions = {
    from: "amansherpa70@gmail.com",
    to: [awb.shipper.shipperEmail, awb.receiver.consigneeEmail],
    subject: `AWB Generated ${awb.trackingNo}`,
    html: `
      <p>Hi ${awb.shipper.shipperName},</p>
      <p>An AWB has been generated by the consignee:${awb.receiver.consigneeName}</p>
      <ul>
        <li>Tracking Number: ${awb.trackingNo}</li>
      </ul>
      <p>Please click <a href="http://localhost:3000/shipper/confirm?trackingNo=${awb.trackingNo}">here</a> to confirm the request</p>
    `,
  };

  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.log(error);
      return res.status(500).json({
        message: "Something went wrong",
      });
    }

    res.status(200).json({ message: "Email Sent successfully", info });
  });
};
